const Theme = {
  global: {
    colors: {
      brand: "#70a9a4",
      secondarybrand: "#94bebb",
      darkbrand: "#7c8a89",
      accent: "#a97075",
      secondaryaccent: "#92a970",
      background: "#edf4f4",
      darkbackground: "#c4c8c8",
      lightbackground: "#f3f5f5",
      white: "#ffffff",
      red: "#ea6262",
      amber: "#eaae62",
      green: "#92a970",
      "background-front": "#1c1f2a",
      text: "#0e0f15",
      "text-strong": "#E6E6E6",
    },
    font: {
      family: `Frutiger LT,
                  -apple-system,
                  BlinkMacSystemFont,
                  "Segoe UI",
                  Roboto,
                  Oxygen,
                  Ubuntu,
                  Cantarell,
                  "Fira Sans",
                  "Droid Sans",
                  "Helvetica Neue",
                  Arial, sans-serif,
                  "Apple Color Emoji",
                  "Segoe UI Emoji",
                  "Segoe UI Symbol"`,
    },
  },
};

export default Theme;
